apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: primavera3d
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- name: ghcr.io/madfam-org/primavera3d/web
  newName: ghcr.io/madfam-org/primavera3d/web
