apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: primavera3d
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:a59b8186f1f5d015e3cc72e7c8fe807b8fbfa6d68dcb3631e848f41d848e3b1c
  name: ghcr.io/madfam-org/primavera3d/web
  newName: ghcr.io/madfam-org/primavera3d/web
