apiVersion: v1
kind: Service
metadata:
  name: primavera3d-web
  namespace: primavera3d
spec:
  type: ClusterIP
  selector:
    app: primavera3d-web
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
